/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  at: Generated<Timestamp>;
  details: Json | null;
  entity: string;
  entity_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  residence_id: string | null;
  user_id: string | null;
}

export interface FollowUps {
  assigned_to: string | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  closing_note: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  due_at: Timestamp | null;
  id: Generated<string>;
  note_id: string;
  residence_id: string;
}

export interface Handovers {
  acknowledged_at: Generated<Timestamp>;
  id: Generated<string>;
  residence_id: string;
  user_id: string;
}

export interface NoteCategories {
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string;
  residence_id: string;
  sort_order: Generated<number>;
}

export interface NoteReads {
  note_id: string;
  read_at: Generated<Timestamp>;
  residence_id: string;
  user_id: string;
}

export interface Notes {
  author_id: string;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  category_id: string;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  intervention: string | null;
  is_positive: Generated<boolean>;
  is_priority: Generated<boolean>;
  occurred_at: Timestamp;
  residence_id: string;
  resident_id: string | null;
  search: Generated<string | null>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface NoteVersions {
  edited_at: Generated<Timestamp>;
  edited_by: string;
  id: Generated<string>;
  note_id: string;
  previous: Json;
  residence_id: string;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Residences {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  timezone: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Residents {
  admitted_at: Timestamp | null;
  birth_date: Timestamp | null;
  created_at: Generated<Timestamp>;
  emergency_contact: string | null;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  left_at: Timestamp | null;
  residence_id: string;
  restricted_notes: string | null;
  room: string | null;
  special_instructions: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  last_name: string;
  password_hash: string;
  residence_id: string | null;
  role: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_log: AuditLog;
  follow_ups: FollowUps;
  handovers: Handovers;
  note_categories: NoteCategories;
  note_reads: NoteReads;
  note_versions: NoteVersions;
  notes: Notes;
  refresh_tokens: RefreshTokens;
  residences: Residences;
  residents: Residents;
  users: Users;
}
